name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
        
    - name: Install dependencies
      working-directory: ./app
      run: npm ci
      
    - name: Run linter
      working-directory: ./app
      run: npm run lint
      
    - name: Run tests
      working-directory: ./app
      run: npm run test:coverage
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./app/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run npm audit
      working-directory: ./app
      run: |
        npm audit --audit-level high
        npm audit fix --dry-run
        
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=app/package.json
        
  build:
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
        
    - name: Install dependencies
      working-directory: ./app
      run: npm ci
      
    - name: Build application
      working-directory: ./app
      run: npm run build
      
    - name: Create build artifact
      run: |
        tar -czf app-build.tar.gz app/
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-build-${{ github.sha }}
        path: app-build.tar.gz
        retention-days: 30